name: Create release changelog

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release-changelog:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Build release changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configuration: ".github/workflows/configs/release-changelog-config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release changelog
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          omitPrereleaseDuringUpdate: true
          body: ${{ steps.github_release.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
